# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cocqJ1NiqQS5HSEswvBrJk8i5H-fxx95
"""

# 1. Installation des dépendances (à exécuter dans la première cellule de votre Colab)
!pip install ultralytics roboflow matplotlib opencv-python

# 2. Importation des bibliothèques nécessaires
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# 3. Chargement du modèle YOLOv8 pré-entraîné (version 'nano' pour la rapidité)
# Cela nous sert de baseline avant d'entraîner notre propre modèle la semaine prochaine.
model = YOLO('yolov8n.pt')

# 4. Chemin vers votre image d'exploration
# Remplacez l'URL par le chemin local d'une image de votre dataset BDD100K une fois téléchargé.
# Ici, on utilise une image de test standard pour vérifier que tout fonctionne.
image_path = 'https://ultralytics.com/images/bus.jpg'

# 5. Lancer l'inférence (la détection d'objets)
results = model(image_path)

# 6. Récupérer et afficher l'image annotée
# .plot() dessine automatiquement les bounding boxes, les classes et les scores de confiance
annotated_frame = results[0].plot()

# Convertir l'image de BGR (format OpenCV) à RGB (format Matplotlib) pour conserver les vraies couleurs
annotated_frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)

# Affichage avec Matplotlib
plt.figure(figsize=(12, 8))
plt.imshow(annotated_frame_rgb)
plt.axis('off')
plt.title("Baseline YOLOv8 - Détection d'objets (Semaine 1)")
plt.show()

# Afficher un résumé textuel dans la console
print(f"Nombre total d'objets détectés dans la scène : {len(results[0].boxes)}")

from roboflow import Roboflow

# Téléchargement du dataset sur ta nouvelle machine GPU
rf = Roboflow(api_key="iZWNoe0hTE92fVWfMcLi")
project = rf.workspace("dions-workspace-m39hz").project("bdd100k-3zgda-hoazu")
version = project.version(1)
dataset = version.download("yolov8")

from ultralytics import YOLO
import os

# 1. On récupère le chemin exact du fichier YAML généré par Roboflow
yaml_path = f"{dataset.location}/data.yaml"
print(f"✅ Fichier YAML prêt à l'adresse : {yaml_path}")

# 2. On charge le modèle YOLOv8 nano
model_n = YOLO('yolov8n.pt')

# 3. On lance l'entraînement propulsé par le GPU T4
print("🚀 Démarrage de l'entraînement...")
results_n = model_n.train(
    data=yaml_path,
    epochs=20,
    imgsz=640,
    batch=16,
    name='yolov8n_autoroute',
    plots=True,
    workers=2  # Accélère le chargement des images
)

!pip install groq

import json
from groq import Groq

# Tu devras mettre ta propre clé API Groq (gratuite sur console.groq.com)
client = Groq(api_key="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")

# 1. Définition de l'outil externe
def calculateur_distance_securite(vitesse_kmh):
    """Calcule la distance de sécurité minimale sur autoroute."""
    # Règle des 2 secondes
    distance_metres = (vitesse_kmh * 1000 / 3600) * 2
    return round(distance_metres, 2)

# 2. Simulation de la sortie de ton modèle YOLO (Module A)
detections_yolo = {
    "vitesse_vehicule": 130,
    "meteo": "degage",
    "objets": [
        {"classe": "voiture", "position": "devant", "distance_estimee_m": 40},
        {"classe": "camion", "position": "voie_droite", "distance_estimee_m": 150}
    ]
}

# 3. Le System Prompt [cite: 50]
system_prompt = """
Tu es un Analyseur Intelligent de Scènes de Conduite.
Ton contexte : Conduite sur AUTOROUTE (Grande vitesse, changements de voie).
Tu reçois des données JSON de détection d'objets.
Tu dois :
1. Analyser les distances et les risques.
2. Évaluer le niveau de risque EXACTEMENT parmi : Faible / Moyen / Élevé / Critique.
3. Rédiger un rapport concis en français avec des recommandations.
"""

# 4. Exécution de l'Agent
def agent_analyse_scene(detections):
    # L'agent utilise son outil
    dist_requise = calculateur_distance_securite(detections["vitesse_vehicule"])

    # On prépare le message pour le LLM
    prompt_utilisateur = f"""
    Voici les détections de la dashcam : {json.dumps(detections)}
    Information outil : La distance de sécurité requise à {detections["vitesse_vehicule"]} km/h est de {dist_requise} mètres.
    Génère le rapport d'analyse.
    """

    # Appel à l'API Groq avec un modèle à jour
    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt_utilisateur}
        ],
        model="llama-3.1-8b-instant", # <-- CORRECTION ICI : Utilisation du modèle Llama 3.1
        temperature=0.2
    )

    return response.choices[0].message.content
# 5. Test du pipeline
print("--- RAPPORT DE L'AGENT LLM ---")
print(agent_analyse_scene(detections_yolo))

import os
import glob
import json
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
from groq import Groq

# --- 1. CONFIGURATION ---
# Insère ta clé API Groq ici
client = Groq(api_key="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")

# On charge TON modèle fine-tuné (celui que tu viens d'entraîner !)
# S'il ne trouve pas le chemin, remplace par 'yolov8n.pt'
chemin_modele = 'runs/detect/yolov8n_autoroute/weights/best.pt'
if not os.path.exists(chemin_modele):
    chemin_modele = 'yolov8n.pt'
model_vision = YOLO(chemin_modele)

# On récupère 3 images au hasard de ton dossier de validation BDD100K
# (Assure-toi que la variable dataset.location est toujours en mémoire, sinon remets le chemin manuel)
chemin_images_val = f"{dataset.location}/valid/images/*.jpg"
images_a_tester = glob.glob(chemin_images_val)[:3] # On prend les 3 premières

# --- 2. FONCTIONS DE L'AGENT LLM ---
def calculateur_distance_securite(vitesse_kmh):
    """Calcule la distance de sécurité minimale (Règle des 2 secondes)."""
    return round((vitesse_kmh * 1000 / 3600) * 2, 2)

system_prompt = """
Tu es un Analyseur Intelligent de Scènes de Conduite sur AUTOROUTE.
Tu reçois des données JSON. Tu dois :
1. Évaluer le niveau de risque parmi : Faible / Moyen / Élevé / Critique.
2. Rédiger un rapport d'analyse concis en français (max 4 phrases) avec des recommandations de conduite.
"""

def agent_analyse_scene(detections):
    dist_requise = calculateur_distance_securite(detections["vitesse_vehicule"])
    prompt_utilisateur = f"""
    Détections dashcam : {json.dumps(detections)}
    Info : Distance de sécurité requise à {detections["vitesse_vehicule"]} km/h = {dist_requise} m.
    Génère le rapport.
    """
    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt_utilisateur}
        ],
        model="llama-3.1-8b-instant",
        temperature=0.2
    )
    return response.choices[0].message.content

# --- 3. BOUCLE D'ANALYSE (LE PIPELINE COMPLET) ---
for chemin_img in images_a_tester:
    print("-" * 50)
    print(f"📸 Analyse de l'image : {os.path.basename(chemin_img)}")

    # ÉTAPE A : VISION (YOLO)
    # Lancer la détection sur l'image
    resultats = model_vision(chemin_img, verbose=False)[0]

    # Affichage de l'image avec matplotlib
    img_annotee = resultats.plot()
    img_rgb = cv2.cvtColor(img_annotee, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(8, 5))
    plt.imshow(img_rgb)
    plt.axis('off')
    plt.show()

    # ÉTAPE B : CONVERSION EN JSON POUR LE LLM
    # On lit les boîtes (boxes) trouvées par YOLO pour créer notre dictionnaire
    objets_detectes = []
    for box in resultats.boxes:
        nom_classe = resultats.names[int(box.cls)]
        confiance = float(box.conf)

        # Astuce : On estime la position selon la coordonnée X de la boîte
        x_center = float(box.xywh[0][0])
        img_width = resultats.orig_shape[1]
        if x_center < img_width / 3:
            position = "gauche"
        elif x_center > 2 * img_width / 3:
            position = "droite"
        else:
            position = "devant (centre)"

        objets_detectes.append({
            "classe": nom_classe,
            "confiance": round(confiance, 2),
            "position": position
        })

    # On simule une vitesse pour l'autoroute (tu pourrais la rendre aléatoire)
    donnees_json = {
        "vitesse_vehicule": 130,
        "objets": objets_detectes
    }

    # ÉTAPE C : RAISONNEMENT DE L'AGENT LLM
    print("🤖 Rapport de l'Agent IA :")
    try:
        rapport = agent_analyse_scene(donnees_json)
        print(rapport)
    except Exception as e:
        print(f"Erreur avec l'API Groq : {e}")
    print("\n")

import os
import glob
import json
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
from groq import Groq

# --- 1. CONFIGURATION ---
client = Groq(api_key="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") # Remets ta clé ici

chemin_modele = 'runs/detect/yolov8n_autoroute/weights/best.pt'
if not os.path.exists(chemin_modele):
    chemin_modele = 'yolov8n.pt'
model_vision = YOLO(chemin_modele)

# On récupère 3 images au hasard
chemin_images_val = f"{dataset.location}/valid/images/*.jpg"
images_a_tester = glob.glob(chemin_images_val)[:20]

# --- 2. LE PROMPT DE L'AGENT LLM ---
system_prompt = """
Tu es un Analyseur Intelligent de Scènes de Conduite.
Tu reçois une liste d'objets détectés sur la route (le trafic en sens inverse a déjà été filtré par le système).

Tes règles d'analyse sont STRICTES :
- RÈGLE 1 : S'il y a un objet décrit comme "très grand / très proche", c'est une urgence. Le niveau de risque est "Élevé" ou "Critique", et tu dois ABSOLUMENT dire de "réduire la vitesse".
- RÈGLE 2 : Les objets "petits / éloignés" ne représentent pas de danger immédiat.
- RÈGLE 3 : S'il y a plusieurs objets mais qu'aucun n'est "très grand", la situation est normale. Le niveau de risque est "Faible" ou "Moyen".
- RÈGLE 4 : Ne mentionne pas de vitesse exacte en km/h, le véhicule n'a pas de radar.

Évalue le niveau de risque (Faible / Moyen / Élevé / Critique) et rédige un rapport concis en 3 phrases maximum.
"""

def agent_analyse_scene(detections):
    prompt_utilisateur = f"Voici les objets pertinents détectés sur notre voie : {json.dumps(detections)}\nGénère le rapport."

    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt_utilisateur}
        ],
        model="llama-3.1-8b-instant",
        temperature=0.1 # Encore plus bas pour qu'il respecte strictement tes règles
    )
    return response.choices[0].message.content

# --- 3. BOUCLE D'ANALYSE (LE PIPELINE) ---
for chemin_img in images_a_tester:
    print("-" * 50)
    print(f"📸 Analyse de l'image : {os.path.basename(chemin_img)}")

    # ÉTAPE A : VISION (YOLO)
    resultats = model_vision(chemin_img, verbose=False)[0]

    # Affichage
    img_annotee = resultats.plot()
    img_rgb = cv2.cvtColor(img_annotee, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(8, 5))
    plt.imshow(img_rgb)
    plt.axis('off')
    plt.show()

    # ÉTAPE B : FILTRAGE INTELLIGENT
    objets_detectes = []
    img_width = resultats.orig_shape[1]
    img_height = resultats.orig_shape[0]
    img_area = img_width * img_height

    for box in resultats.boxes:
        nom_classe = resultats.names[int(box.cls)]
        x_center = float(box.xywh[0][0])

        # 1. IGNORER LE SENS INVERSE (Le quart gauche de l'image)
        if x_center < (img_width * 0.25):
            continue

        # 2. ÉVALUER LA PROXIMITÉ (Taille de la boîte)
        box_width = float(box.xywh[0][2])
        box_height = float(box.xywh[0][3])
        box_area_ratio = (box_width * box_height) / img_area

        if box_area_ratio > 0.10: # Si l'objet prend plus de 15% de l'image
            taille = "très grand / très proche"
        elif box_area_ratio > 0.04:
            taille = "moyen"
        else:
            taille = "petit / éloigné"

        objets_detectes.append({
            "classe": nom_classe,
            "proximite": taille
        })

    # ÉTAPE C : RAISONNEMENT LLM
    print("🤖 Rapport de l'Agent IA :")
    try:
        # Si la liste est vide après avoir ignoré le trafic inverse
        if len(objets_detectes) == 0:
            print("Aucun objet dangereux détecté sur notre voie. Risque: Faible. Vous pouvez maintenir votre allure.")
        else:
            rapport = agent_analyse_scene(objets_detectes)
            print(rapport)
    except Exception as e:
        print(f"Erreur avec l'API Groq : {e}")
    print("\n")